version: "3.7"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-dev
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - "./mysql:/docker-entrypoint-initdb.d/:ro"
